/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.26
 * Generated at: 2024-11-02 10:54:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import test.*;
import java.util.*;

public final class UserViewBooks_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("test");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>View Books - SAIBOOKS</title>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("    <link rel=\"icon\" href=\"images/logo.png\" type=\"image/png\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <img src=\"images/logo.png\" alt=\"SAIBOOKS Logo\" class=\"logo\">\r\n");
      out.write("        <h1>SAIBOOKS</h1>\r\n");
      out.write("    </header>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <nav>\r\n");
      out.write("            <a href=\"viewCart\">View Cart</a>\r\n");
      out.write("            <a href=\"UserLogin.jsp\">Back</a>\r\n");
      out.write("            <a href=\"logout\">Logout</a>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <h2>Book List</h2>\r\n");
      out.write("        ");

            String msg = (String) request.getAttribute("msg");
            if (msg != null) {
                out.print("<p style='color: red;'>" + msg + "</p>");
            }
            ArrayList<BookBean> al = (ArrayList<BookBean>) session.getAttribute("al");
            if (al == null || al.isEmpty()) {
                out.println("<p>No books available.</p>");
            } else {
        
      out.write("\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>Serial No.</th>\r\n");
      out.write("                <th>Book Image</th>\r\n");
      out.write("                <th>Book Code</th>\r\n");
      out.write("                <th>Book Name</th>\r\n");
      out.write("                <th>Author</th>\r\n");
      out.write("                <th>Price</th>\r\n");
      out.write("                <th>Quantity</th>\r\n");
      out.write("                <th>Action</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");

            int serialNo = 1; // Initialize the serial number counter
            for (BookBean bb : al) {
                String bookImage; // Declare variable for book image
                switch (bb.getCode()) {
                    case "A100":
                        bookImage = "images/A100.png";
                        break;
                    case "A101":
                        bookImage = "images/A101.png";
                        break;
                    case "A102":
                        bookImage = "images/A102.png";
                        break;
                    case "A103":
                        bookImage = "images/A103.png";
                        break;
                    case "A104":
                        bookImage = "images/A104.png";
                        break;
                    case "A105":
                        bookImage = "images/A105.png";
                        break;
                    case "A106":
                        bookImage = "images/A106.png";
                        break;
                    case "A107":
                        bookImage = "images/A107.png";
                        break;
                    case "A108":
                        bookImage = "images/A108.png";
                        break;
                    case "A109":
                        bookImage = "images/A109.png";
                        break;
                    case "A110":
                        bookImage = "images/A110.png";
                        break;
                    case "A111":
                        bookImage = "images/A111.png";
                        break;
                    case "A112":
                        bookImage = "images/A112.png";
                        break;
                    case "A113":
                        bookImage = "images/A113.png";
                        break;
                    case "A114":
                        bookImage = "images/A114.png";
                        break;
                    case "A115":
                        bookImage = "images/A115.jpg";
                        break;
                    case "A116":
                        bookImage = "images/A116.png";
                        break;
                    case "A117":
                        bookImage = "images/A117.png";
                        break;
                    case "A118":
                        bookImage = "images/A118.png";
                        break;
                    case "A119":
                        bookImage = "images/A119.png";
                        break;
                    case "A120":
                        bookImage = "images/A120.png";
                        break;
                    default:
                        bookImage = "images/logo.png"; // Fallback image
                        break;
                }
            
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>");
      out.print( serialNo++ );
      out.write("</td>\r\n");
      out.write("                <td><img src=\"");
      out.print( bookImage );
      out.write("\" alt=\"");
      out.print( bb.getName() );
      out.write(" Image\" class=\"book-image\"></td>\r\n");
      out.write("                <td>");
      out.print( bb.getCode() );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( bb.getName() );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( bb.getAuthor() );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( bb.getPrice() );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( bb.getQty() );
      out.write("</td>\r\n");
      out.write("                <td><a href=\"buy?bcode=");
      out.print( bb.getCode() );
      out.write("\">Add to Cart</a></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");

                }
            
      out.write("\r\n");
      out.write("        </table>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
